foreground = #ffffff
background = #15191b
selection-foreground = #484a4b
selection-background = #2b95ff

cursor-color = #2b95ff
cursor-text = #111111
split-divider-color = #434343

palette = 0=#292b2d
palette = 1=#f30928
palette = 2=#00d96b
palette = 3=#e3b341
palette = 4=#2b95ff
palette = 5=#bc8cff
palette = 6=#39c5cf
palette = 7=#ffffff
palette = 8=#676767
palette = 9=#ff4b5c
palette = 10=#00ff88
palette = 11=#e3b341
palette = 12=#5fafff
palette = 13=#d2a8ff
palette = 14=#56d4dd
palette = 15=#ffffff
