[v1]
"cargo-edit 0.13.13 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-update 22.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"neetcode-log 0.1.0 (path+file:///Users/matt/src/gleich/neetcode/script)" = ["neetcode-log"]
"resin 1.6.8 (path+file:///Users/matt/src/gleich/resin)" = ["resin"]
