complete -c optic -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c optic -n "__fish_use_subcommand" -f -a "new" -d 'Create a new branch'
complete -c optic -n "__fish_use_subcommand" -f -a "build" -d 'Build a branch'
complete -c optic -n "__fish_use_subcommand" -f -a "watch" -d 'View a branch and build it on change'
complete -c optic -n "__fish_use_subcommand" -f -a "open" -d 'Open a branch in an editor'
complete -c optic -n "__fish_use_subcommand" -f -a "reveal" -d 'Open a branch PDF in finder'
complete -c optic -n "__fish_use_subcommand" -f -a "check" -d 'Check to see if any branches don\'t have up-to-date PDFs'
complete -c optic -n "__fish_use_subcommand" -f -a "trash" -d 'Move branch to trash can'
complete -c optic -n "__fish_use_subcommand" -f -a "completion" -d 'Generate shell completion for optic'
complete -c optic -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c optic -n "__fish_seen_subcommand_from new" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from build" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from watch" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from open" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from reveal" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from check" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from trash" -s h -l help -d 'Print help information'
complete -c optic -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Print help information'
