local settings = {
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        content = {
            "                     ⣀⣀⣀⣀                       ",
            "             ⣀⣤⣤⣤⡄⢀⠰⠿⣿⣿⣿⠿⠛⣂⡀⢴⣶⣦⣤⣀               ",
            "           ⠰⠿⠿⠿⠿⠋⠴⠿⠿⠖⠂⠨⠐⠚⠿⠿⠿⠦⠙⠿⠿⠿⠷              ",
            "       ⣀⣤⡖⣰⣶⣶⡶⠂⠔⢂⣠⣴⣶⣶⣶⣶⣶⣶⣶⣶⣤⣄⣐⠢⠐⢶⣶⣶⡐⣶⣤⣀         ",
            "      ⣼⣿⡿⠠⠟⠛⢉⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⡈⢙⡓⠘⢿⣿⣧⡀       ",
            "     ⠸⢛⣉⢁⡶⢋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡙⢧⠰⣤⣍⡃       ",
            "   ⣠⡄⢸⣿⠏⢈⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⢻⣿⡇⢸⣦     ",
            "  ⣼⣿⡇⠸⠋⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠙⠇⢸⣿⣷    ",
            " ⢰⣿⡿⠃⢰⢡⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡌⠆⠘⢿⣿    ",
            " ⠈⢋⣴⡇ ⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⠿⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⢸⣦⡉    ",
            " ⣴⠘⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡱⡈⣦⡡⣢⣍⢶⣩⢔⣬⢱⡎⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠘⡿⢠⣦   ",
            "⢸⣿⣧⠹ ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⣣⢱⡟⣼⣿⡇⣿⢣⣿⡿⣸⡇⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢠⠁⣿⣿⡇  ",
            "⢸⣿⣿⢀⠁⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⣾⢣⣿⣿⢱⡏⣾⣿⢇⡿⣸⢫⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇ ⣄⢻⣿⡇  ",
            " ⠻⠇⣼⡆⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢱⡟⣼⣿⡏⣾⢱⣿⣿⠸⣇⡣⢣⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢰⣿⡆⠟⠁  ",
            "  ⣈⠻⡇⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣷⣶⣿⣿⣿⣷⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⢸⡿⢋⡀   ",
            "  ⣿⣷⡄⠰⡘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⡆⢈⣴⣿⡇   ",
            "  ⢻⣿⡇⢰⣄⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⢈⡄⢸⣿⡿    ",
            "   ⠻⡇⢸⣿⣧⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⢰⣿⡇⠸⠋     ",
            "     ⢈⣙⠛⠆⢳⣌⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋⠴⠁⣋⣥⡄       ",
            "      ⢻⣿⣷⡄⢨⣁⡈⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⢋⣠⣴⠆⣾⣿⡿⠁       ",
            "       ⠉⠻⠿⠌⠿⠿⠷ ⠢⠍⠙⠛⠿⠿⠿⠿⠿⠿⠿⠿⠟⠛⠩⠴⠂⠴⠿⠿⠏⠸⠟⠋         ",
            "            ⢶⣶⣶⣶⣄⠲⣶⣶⣶⡤ ⠒⠠⢤⣶⣶⡶⢂⣴⣶⣶⣶⠖             ",
            "             ⠉⠛⠿⠿⠗⠈⠉⣥⣶⣿⣿⣿⣶⠤⠉⠐⠛⠛⠛⠋⠁              ",
            "                     ⠉⠉⠉⠉⠁                      ",
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
    body = {
        type = "mapping",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Basic Commands",
        margin = 5,
        content = {
            { "λ LOC  f", "Telescope find_files", "f" },
            { "μ LOC rf", "Telescope oldfiles", "rf" },
            { "Σ COL", "Telescope colorscheme", "co" },
            { "δ FSB", "Telescope file_browser", "fb" },
            { " NF", "lua require'startup'.new_file()", "nf" },
        },
        highlight = "String",
        default_color = "",
        oldfiles_amount = 0,
    },
    footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 5,
        content = { "mattglei.ch" },
        highlight = "Number",
        default_color = "",
        oldfiles_amount = 0,
    },
    options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 3, 3, 0 },
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "body", "footer" },
}

return settings
