tap "alexellis/alexellis"
tap "dart-lang/dart"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "matt-gleich/taps"
tap "nektos/tap"
tap "rodionovd/taps"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Python code formatter
brew "black"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Platform built on V8 to build network applications
brew "node"
# Unfancy JavaScript
brew "coffeescript"
# Configurable talking characters in ASCII art
brew "cowsay"
# Isolated development environments using Docker
brew "docker-compose"
# GitHub command-line tool
brew "gh"
# Emoji guide for your commit messages
brew "gitmoji"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Version Control Visualization Tool
brew "gource"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Python package management tool
brew "poetry"
# Show ps output as a tree
brew "pstree"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Digital clock in ncurses
brew "tty-clock"
# Executes a program periodically, showing output fullscreen
brew "watch"
# JavaScript package manager
brew "yarn"
# Install k3s over SSH with ('ketchup')
brew "alexellis/alexellis/k3sup"
# The Dart SDK
brew "dart-lang/dart/dart"
# Fast linters runner for Go.
brew "golangci/tap/golangci-lint"
# ☢️ Force quit all applications with one terminal command
brew "matt-gleich/taps/nuke"
# Run GitHub Actions locally
brew "nektos/tap/act"
# CLI manager for your text replacements on macOS
brew "rodionovd/taps/shortcuts"
cask "adobe-creative-cloud"
cask "alacritty"
cask "alfred"
cask "android-studio"
cask "bartender"
cask "brave-browser"
cask "cheatsheet"
cask "cool-retro-term"
cask "discord"
cask "docker"
cask "drawio"
cask "edex-ui"
cask "font-3270"
cask "font-fira-code"
cask "github"
cask "gitify"
cask "grammarly"
cask "hyper"
cask "iterm2"
cask "kite"
cask "lastpass"
cask "logitech-options"
cask "mactex"
cask "opera"
cask "phoenix"
cask "postman"
cask "slack"
cask "steam"
cask "virtualbox"
cask "visual-studio-code"
cask "zoomus"
